from tkinter import*
V=Tk()
V.geometry("1000x500")
miFrame=Frame(V, width="400",height="300" , bg="darkgreen")
miFrame.place(x=1, y=1)
label01=Label(miFrame, text="Tengo sueño")
label01.place(x=4, y=10)
label01.config(bg="red",fg="blue")
label01.config(font=("Agency Fb" , 20))
V.mainloop()
