V=True
F=False
print("")
print("============================================================================================")
print("")
print("Negar NOT si algo es falso lo convierte \en verdad y si algo es verdadero")
print("lo convierte en falso")
print("")
print(not V)
print(not F)
print("")
print("============================================================================================")
print("")
print("Conjucion AND Todas las condiciones deben ser V \ tienen que cumplirse")
print(v and v)
print(v and f)
print(f and v)
print(f and f)
print("")
print("============================================================================================")
print("")
print(v or v)
print(v or f)
print(f or v)
print(f or f or v)
print(f or f or f)
print("")
print("============================================================================================")
print("")
